version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: cryptovault_db
      POSTGRES_USER: cryptovault_user
      POSTGRES_PASSWORD: wspa012026
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  app:
    build: .
    container_name: spring-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      # 1. Явно включаем PROD профиль
      SPRING_PROFILES_ACTIVE: prod

      # 2. Настройки БД (используем имя сервиса 'postgres' как хост)
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cryptovault_db
      SPRING_DATASOURCE_USERNAME: cryptovault_user
      SPRING_DATASOURCE_PASSWORD: wspa012026

      # 3. Переопределяем пути для Docker (Linux)
      # Скрипты мы скопировали в /app/scripts в Dockerfile
      CRYPTOVAULT_SCRIPTS_PATH: /app/scripts
      # В Linux команда обычно python3
      CRYPTOVAULT_SCRIPTS_PYTHON_EXECUTABLE: python3

      # 4. Пути для сохранения файлов внутри контейнера
      CRYPTOVAULT_STORAGE_PATH: /app/uploads
      CRYPTOVAULT_REPORTS_OUTPUT_PATH: /app/reports

    # 5. Чтобы файлы не исчезли после перезапуска контейнера, монтируем их на хост
    volumes:
      - ./docker_data/uploads:/app/uploads
      - ./docker_data/reports:/app/reports

volumes:
  pgdata: